import type { ParamSchema } from '../../core';

export const NOISE_TYPES = ['white', 'pink', 'chip', 'chip-metal'] as const;
export const FILTER_TYPES = ['lowpass', 'highpass', 'bandpass'] as const;
export const SWEEP_CURVES = ['lin', 'exp'] as const;
export const SEQ_MODES = ['step', 'glide', 'retrigger'] as const;
export const SEQ_SCALES = ['chromatic', 'major', 'minor', 'pentatonic', 'octaves'] as const;
export const SPEAKER_MODELS = ['off', 'phone', 'laptop', 'piezo', 'handheld', 'tv'] as const;

/**
 * Beep synth parameters. `randomRange`s are tuned so one-click randomise lands on short,
 * usable UI and game blips most of the time rather than the full extremes of each control.
 */
export const beepSchema = {
  // Oscillator
  shape: {
    kind: 'number',
    label: 'Shape',
    group: 'Oscillator',
    min: 0,
    max: 4,
    default: 0,
    hint: 'Morphs sine (0) → triangle (1) → saw (2) → square (3) → pulse (4)',
  },
  pulseWidth: {
    kind: 'number',
    label: 'Pulse width',
    group: 'Oscillator',
    min: 0.05,
    max: 0.5,
    default: 0.25,
    hint: 'Duty cycle reached at shape 4',
  },
  coarse: {
    kind: 'number',
    label: 'Coarse',
    group: 'Oscillator',
    min: -24,
    max: 24,
    default: 0,
    step: 1,
    unit: 'st',
    randomRange: [-12, 12],
  },
  fine: {
    kind: 'number',
    label: 'Fine',
    group: 'Oscillator',
    min: -100,
    max: 100,
    default: 0,
    unit: 'ct',
    randomRange: [-10, 10],
  },
  oscLevel: {
    kind: 'number',
    label: 'Osc level',
    group: 'Oscillator',
    min: 0,
    max: 1,
    default: 1,
    randomRange: [0.6, 1],
  },

  // FM
  fmRatio: {
    kind: 'number',
    label: 'Ratio',
    group: 'FM',
    min: 0.25,
    max: 16,
    default: 2,
    step: 0.25,
    curve: 'log',
    unit: 'x',
    randomRange: [0.5, 8],
  },
  fmIndex: {
    kind: 'number',
    label: 'Amount',
    group: 'FM',
    min: 0,
    max: 20,
    default: 0,
    randomRange: [0, 4],
    hint: 'Modulation index: 0 is off',
  },
  fmDecay: {
    kind: 'number',
    label: 'FM decay',
    group: 'FM',
    min: 0.005,
    max: 4,
    default: 0.2,
    curve: 'log',
    unit: 's',
    randomRange: [0.01, 0.5],
  },

  // Noise
  noiseType: { kind: 'enum', label: 'Noise', group: 'Noise', options: NOISE_TYPES, default: 'white' },
  noiseLevel: {
    kind: 'number',
    label: 'Noise level',
    group: 'Noise',
    min: 0,
    max: 1,
    default: 0,
    randomRange: [0, 0.5],
  },
  noiseFilter: {
    kind: 'number',
    label: 'Noise tone',
    group: 'Noise',
    min: 100,
    max: 20000,
    default: 12000,
    curve: 'log',
    unit: 'Hz',
    hint: 'Low-pass on the noise only',
  },

  // Pitch
  sweep: {
    kind: 'number',
    label: 'Sweep start',
    group: 'Pitch',
    min: -48,
    max: 48,
    default: 0,
    unit: 'st',
    randomRange: [-24, 24],
    hint: 'Pitch offset the note starts at, sweeping to the played pitch',
  },
  sweepTime: {
    kind: 'number',
    label: 'Sweep time',
    group: 'Pitch',
    min: 0.001,
    max: 2,
    default: 0.08,
    curve: 'log',
    unit: 's',
    randomRange: [0.01, 0.4],
  },
  sweepCurve: { kind: 'enum', label: 'Sweep curve', group: 'Pitch', options: SWEEP_CURVES, default: 'lin' },
  pitchEnv: {
    kind: 'number',
    label: 'Env depth',
    group: 'Pitch',
    min: -24,
    max: 24,
    default: 0,
    unit: 'st',
    randomRange: [-7, 7],
  },
  pitchAttack: {
    kind: 'number',
    label: 'Env attack',
    group: 'Pitch',
    min: 0.001,
    max: 1,
    default: 0.005,
    curve: 'log',
    unit: 's',
    randomRange: [0.001, 0.05],
  },
  pitchDecay: {
    kind: 'number',
    label: 'Env decay',
    group: 'Pitch',
    min: 0.005,
    max: 2,
    default: 0.1,
    curve: 'log',
    unit: 's',
    randomRange: [0.01, 0.3],
  },

  // Vibrato
  vibratoRate: {
    kind: 'number',
    label: 'Rate',
    group: 'Vibrato',
    min: 0.5,
    max: 30,
    default: 6,
    curve: 'log',
    unit: 'Hz',
  },
  vibratoDepth: {
    kind: 'number',
    label: 'Depth',
    group: 'Vibrato',
    min: 0,
    max: 200,
    default: 0,
    unit: 'ct',
    randomRange: [0, 30],
  },
  vibratoDelay: {
    kind: 'number',
    label: 'Delay',
    group: 'Vibrato',
    min: 0,
    max: 1,
    default: 0,
    unit: 's',
    randomRange: [0, 0.2],
  },

  // Step sequencer
  seqOn: { kind: 'bool', label: 'Sequencer', group: 'Sequencer', default: false },
  seqSteps: {
    kind: 'steps',
    label: 'Steps',
    group: 'Sequencer',
    length: 16,
    min: -24,
    max: 24,
    step: 1,
    default: [0, 12, 7, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    hint: 'Semitone offset per step',
  },
  seqLength: {
    kind: 'number',
    label: 'Length',
    group: 'Sequencer',
    min: 1,
    max: 16,
    default: 2,
    step: 1,
    randomRange: [2, 6],
  },
  seqRate: {
    kind: 'number',
    label: 'Step time',
    group: 'Sequencer',
    min: 0.01,
    max: 0.5,
    default: 0.06,
    curve: 'log',
    unit: 's',
    randomRange: [0.03, 0.12],
  },
  seqMode: { kind: 'enum', label: 'Mode', group: 'Sequencer', options: SEQ_MODES, default: 'step' },
  seqScale: {
    kind: 'enum',
    label: 'Scale',
    group: 'Sequencer',
    options: SEQ_SCALES,
    default: 'chromatic',
    hint: 'Snaps step values to a scale, so random sequences stay musical',
  },
  seqLoop: { kind: 'bool', label: 'Loop', group: 'Sequencer', default: false },

  // Filter
  filterType: {
    kind: 'enum',
    label: 'Type',
    group: 'Filter',
    options: FILTER_TYPES,
    default: 'lowpass',
    randomize: false,
    hint: 'Not randomised: a random high-pass at a high cutoff would silence the sound',
  },
  cutoff: {
    kind: 'number',
    label: 'Cutoff',
    group: 'Filter',
    min: 40,
    max: 20000,
    default: 20000,
    curve: 'log',
    unit: 'Hz',
    randomRange: [800, 20000],
  },
  resonance: {
    kind: 'number',
    label: 'Resonance',
    group: 'Filter',
    min: 0.1,
    max: 15,
    default: 0.7,
    curve: 'log',
    randomRange: [0.3, 6],
  },
  filterEnv: {
    kind: 'number',
    label: 'Env amount',
    group: 'Filter',
    min: -6,
    max: 6,
    default: 0,
    unit: 'x',
    randomRange: [-2, 3],
    hint: 'Octaves',
  },
  filterDecay: {
    kind: 'number',
    label: 'Env decay',
    group: 'Filter',
    min: 0.005,
    max: 4,
    default: 0.2,
    curve: 'log',
    unit: 's',
    randomRange: [0.02, 0.5],
  },

  // Amp
  attack: {
    kind: 'number',
    label: 'Attack',
    group: 'Amp',
    min: 0.001,
    max: 1,
    default: 0.002,
    curve: 'log',
    unit: 's',
    randomRange: [0.001, 0.03],
  },
  hold: {
    kind: 'number',
    label: 'Hold',
    group: 'Amp',
    min: 0,
    max: 1,
    default: 0,
    unit: 's',
    randomRange: [0, 0.05],
  },
  decay: {
    kind: 'number',
    label: 'Decay',
    group: 'Amp',
    min: 0.005,
    max: 4,
    default: 0.15,
    curve: 'log',
    unit: 's',
    randomRange: [0.03, 0.6],
  },
  sustain: {
    kind: 'number',
    label: 'Sustain',
    group: 'Amp',
    min: 0,
    max: 1,
    default: 0,
    randomRange: [0, 0.5],
  },
  release: {
    kind: 'number',
    label: 'Release',
    group: 'Amp',
    min: 0.005,
    max: 2,
    default: 0.05,
    curve: 'log',
    unit: 's',
    randomRange: [0.01, 0.3],
  },
  velToLevel: {
    kind: 'number',
    label: 'Vel → level',
    group: 'Amp',
    min: 0,
    max: 1,
    default: 1,
    randomize: false,
  },
  velToBright: {
    kind: 'number',
    label: 'Vel → bright',
    group: 'Amp',
    min: 0,
    max: 1,
    default: 0,
    randomize: false,
  },

  // Speaker emulation
  speaker: { kind: 'enum', label: 'Speaker', group: 'Speaker', options: SPEAKER_MODELS, default: 'off' },
  speakerAmount: {
    kind: 'number',
    label: 'Amount',
    group: 'Speaker',
    min: 0,
    max: 1,
    default: 1,
    randomRange: [0.5, 1],
  },
} satisfies ParamSchema;
